# Generated by Django 3.1.7 on 2021-04-11 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_lawyer_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='joined_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 17, 6, 55, 899741)),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='is_sublawyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='joined_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 17, 6, 55, 899741)),
        ),
    ]
