# Generated by Django 3.1.7 on 2021-04-13 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20210411_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='clientprofile'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='lawyerprofile'),
        ),
        migrations.AlterField(
            model_name='client',
            name='joined_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 11, 55, 15, 353095)),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='joined_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 11, 55, 15, 345095)),
        ),
    ]
